export enum PercentageType {
  INSURANCE_REMITTANCE = 'INSURANCE_REMITTANCE',
  RIDER_INITIAL_REMITTANCE = 'RIDER_INITIAL_REMITTANCE',
  TRUCKWYS_PERCENTAGE_FROM_A_RIDE ='TRUCKWYS_PERCENTAGE_FROM_A_RIDE'
}